Replace worldgenoverride.lua with leveldataoverride.lua
yeetzone/docker-dontstarvetogether pull request #85
Opened 2017-07-05 18:05 UTC by thasmo

That should do it. 🤷‍♂️

2017-07-05 21:19 UTC, BraisGabin requested changes

2017-07-05 21:19 UTC, BraisGabin commented on docs/configuration.md
> +**LEVELDATA_OVERRIDES**
You changued the variable name in the docs but the code doesn't use `LEVELDATA_OVERRIDES` it continues using `WORLD_OVERRIDES`.

Probably you must find all the ocurrences of `WORLD_OVERRIDES` and renamed. This is a Breaking Change... but Klei introduced it so I think that it's ok to do it.

2017-07-05 21:53 UTC, thasmo commented on docs/configuration.md
> +**LEVELDATA_OVERRIDES**
Oh, indeed. Not my brightest hour. :D Gonna fix it. Thanks for the check!

2017-07-05 22:11 UTC, thasmo commented on docs/configuration.md
> +**LEVELDATA_OVERRIDES**
Changed it. Also, we still don't have a final release yet, so breaking changes for minor versions are fine for now, I believe.

2017-07-06 08:50 UTC, BraisGabin approved these changes

2017-07-06 08:51 UTC, BraisGabin approved these changes
LGTM

2017-07-06 08:56 UTC, merged